/**
 * prac.config.js — Repository-specific PRaC configuration.
 *
 * This file tells the PRaC toolkit how your repository is set up.
 * It is generated by `npx @ydax/prac-kit init` and should be committed.
 *
 * Every script in lib/ reads this config at startup via loadConfig().
 */

module.exports = {
  // ── Identity ──────────────────────────────────────────────────────────────
  repo: 'ydax/my-repo',             // GitHub org/repo slug
  linearTeamKey: 'MYR',             // Linear team prefix (e.g., HAA, SIG)
  linearTeamId: '',                  // Linear team UUID (from Linear API)
  projectName: 'My Project',        // Human-readable project name

  // ── Paths ─────────────────────────────────────────────────────────────────
  epicsDir: 'epics',                // where epics live (relative to repo root)
  docsDir: 'docs',                  // where docs live (relative to repo root)

  // ── Agent Configuration ───────────────────────────────────────────────────
  julesSourceContext: 'sources/github/ydax/my-repo',
  agentsFile: 'AGENTS.md',

  // Instructions injected into every Jules prompt.
  // Customize these to match your repo's conventions.
  blueprintInstructions: [
    'Read `AGENTS.md` first — it is the universal entry point.',
    'Follow TDA: write failing tests first, then implement.',
    'Update the source STORY.md status to `in_progress` in your first commit, and to `done` in your final commit before opening the PR.',
  ],

  // ── LLM Models ────────────────────────────────────────────────────────────
  orchestratorModel: 'gemini-3-pro-preview',   // used by orchestrate-story.js
  reviewerModel: 'gemini-3-flash-preview',     // used by review-pr.js

  // ── Workflow Behavior ─────────────────────────────────────────────────────
  autoMergeBlueprints: true,         // auto-merge orchestrator PRs (no manual review)
  maxReviewerRevisions: 3,           // max times reviewer retries before escalating
  cascadeEnabled: true,              // auto-trigger next task after merge
  pollIntervalMs: 5 * 60 * 1000,    // 5 minutes between Jules polls

  // ── Linear State IDs ──────────────────────────────────────────────────────
  // These differ per Linear workspace. Find them via the Linear API or UI.
  // Set to null to skip status transitions.
  linearStates: {
    inProgress: null,                // UUID of your "In Progress" state
    done: null,                      // UUID of your "Done" state (null = use default)
  },

  // ── Test Commands ─────────────────────────────────────────────────────────
  // Commands the nightly loop runs. Set to null to skip.
  testCommands: [
    'npm run test:ci',
  ],
};
